name: new_weedus
description: "Weedus"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_dynamic_theme: ^2.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  firebase_database: ^11.1.2
  firebase_analytics: ^11.3.1
  firebase_messaging: ^15.1.1
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.2
  google_fonts: ^6.2.1
  joy_dropdowns: ^1.0.0+1
  flutter_rating_stars: ^1.0.3+4
  flutter_sticky_header: ^0.6.4
  expandable: ^5.0.1
  provider: ^6.0.2
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  side_sheet: ^1.0.3
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.2.1
  fl_chart: ^0.69.0
  iconsax: ^0.0.8
  data_table_2: ^2.3.3
  d_chart: ^2.8.0
  #carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flip_card: ^0.7.0
  custom_pop_up_menu: ^1.2.4
  badges: ^3.1.1
  go_router: ^14.2.7
  # go_router: ^13.2.1
  responsive_grid: ^2.1.0
  image_picker: ^1.0.0
  #image_cropper: ^5.0.1
  image_cropper: ^8.0.1
  dotted_border: ^2.0.0+3
  firebase_auth_web: ^5.8.13
  simple_animations: ^5.0.0+3
  animated_text_kit: ^4.2.2
  flutter_font_icons: ^2.2.5
  widget_and_text_animator: ^1.0.9
  flutter_animate: ^4.1.1+1
  #drop_shadow: ^0.1.0
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_credit_card: ^3.0.7
  mask_text_input_formatter: ^2.4.0
  uuid: ^4.3.3
  #
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  maps_toolkit: ^3.0.0
  flutter_hooks: ^0.21.0
  fading_edge_scrollview: ^4.1.1
  shimmer: ^3.0.0
  dropdown_button2: ^2.1.4
  flutter_staggered_animations: ^1.0.0 #
  lottie: ^3.1.0
  circular_countdown_timer: ^0.2.3
  video_player: ^2.7.2
  flick_video_player: ^0.9.0
  scroll_to_index: ^3.0.1
  responsive_framework: ^1.4.0
  flutter_smart_dialog: ^4.9.7+9
  flutter_cache_manager: ^3.4.1
  pin_code_fields: ^8.0.1
  plaid_flutter: ^3.1.8



  path: any
  cached_network_image: ^3.4.1
  intl_phone_field: ^3.2.0
  easy_localization: ^3.0.7
  firebase_remote_config: ^5.1.1
  google_sign_in_web: ^0.12.4+2
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/accessories/
    - assets/animated/
    - assets/app/
    - assets/apparel/
    - assets/banner/
    - assets/beverages/
    - assets/buds/
    - assets/buds/bud_in_jar/
    - assets/card_icons/
    - assets/card_icons/cards/
    - assets/cbd/
    - assets/concentrates/
    - assets/edibles/
    - assets/effects/
    - assets/growing/
    - assets/map/
    - assets/monogram/
    - assets/preRoll/
    - assets/stiiizy/
    - assets/tinctures/
    - assets/topicals/
    - assets/vaporizers/


  fonts:

    - family: Neuropolitical
      fonts:
        - asset: fonts/Neuropolitical-Regular.otf

    - family: TitanOne
      fonts:
        - asset: fonts/TitanOne-Regular.ttf