import 'package:new_weedus/_helper/helper_export.dart';

class Product {
  String? title,
      tag,
      description,
      product,
      brand,
      type,
      apparelSize,
      pack,
      time,
      orderStatus;

  double? rating,
      price,
      size,
      discount,
      flOz,
      cbd,
      tac,
      thc,
      totalThc,
      totalCbd,
      ml,
      calories,
      strainLimit,
      concentratesLimit;
  int? comment, quantity, stockPieces;
  bool? isSativa, isIndica, isHybrid, isCBD;
  List<String>? images = [];
  List<String>? transparentImages = [];
  List<double>? priceList = [];
  List<double>? sizeList = [];
  List<String>? tagList = [];
  List<String>? extractionMethodList = [];

  Product({this.tag,
    this.images,
    this.transparentImages,
    this.rating,
    this.title,
    this.tac,
    this.thc,
    this.cbd,
    this.price,
    this.description,
    this.brand,
    this.isSativa,
    this.isIndica,
    this.isHybrid,
    this.isCBD,
    this.product,
    this.comment,
    this.size,
    this.discount,
    this.flOz,
    this.ml,
    this.calories,
    this.totalThc,
    this.totalCbd,
    this.type,
    this.apparelSize,
    this.pack,
    this.quantity,
    this.time,
    this.stockPieces,
    this.priceList,
    this.sizeList,
    this.tagList,
    this.strainLimit,
    this.concentratesLimit,
    this.extractionMethodList,
    this.orderStatus});

  factory Product.fromJson(Map<String, dynamic> json) {
    return Product(
        title: json['title'] as String,
        tag: json['tag'] as String,
        description: json['description'] as String,
        product: json['product'] as String,
        tac: json['tac'] as double,
        thc: json['thc'] as double,
        totalThc: json['totalThc'] as double,
        totalCbd: json['totalCbd'] as double,
        cbd: json['cbd'] as double,
        brand: json['brand'] as String,
        type: json['type'] as String,
        apparelSize: json['apparelSize'] as String,
        pack: json['pack'] as String,
        price: json['price'] as double,
        rating: json['rating'] as double,
        size: json['size'] as double,
        discount: json['discount'] as double,
        flOz: json['flOz'] as double,
        ml: json['ml'] as double,
        calories: json['calories'] as double,
        strainLimit: json['strainLimit'] as double,
        concentratesLimit: json['concentratesLimit'] as double,
        comment: json['comment'] as int,
        quantity: json['quantity'] as int,
        isSativa: json['isSativa'] as bool,
        isIndica: json['isIndica'] as bool,
        isHybrid: json['isHybrid'] as bool,
        isCBD: json['isCBD'] as bool,
        images: json['images'].cast<String>(),
        transparentImages: json['transparentImages'].cast<String>(),
        priceList: json['priceList'].cast<double>(),
        sizeList: json['sizeList'].cast<double>(),
        tagList: json['tagList'].cast<String>(),
        extractionMethodList: json['extractionMethodList'].cast<String>(),
        orderStatus: json['orderStatus'] as String);
  }

  Map<String, Object?> toJson() {
    return {
      'tag': tag,
      'images': images,
      'transparentImages': transparentImages,
      'rating': rating,
      'title': title,
      'tac': tac,
      'thc': thc,
      'cbd': cbd,
      'price': price,
      'description': description,
      'brand': brand,
      'isSativa': isSativa,
      'isIndica': isIndica,
      'isHybrid': isHybrid,
      'isCBD': isCBD,
      'product': product,
      'comment': comment,
      'size': size,
      'discount': discount,
      'flOz': flOz,
      'ml': ml,
      'calories': calories,
      'totalThc': totalThc,
      'totalCbd': totalCbd,
      'type': type,
      'apparelSiz': apparelSize,
      'pack': pack,
      'quantity': quantity,
      'sizeList': sizeList,
      'priceList': priceList,
      'tagList': tagList,
      'strainLimit': strainLimit,
      'concentratesLimit': concentratesLimit,
      'extractionMethodList': extractionMethodList,
      'orderStatus': orderStatus
    };
  }

  Product copyWith({
    String? title,
    String? tag,
    String? description,
    String? productType,
    String? brand,
    String? type,
    String? apparelSize,
    String? pack,
    String? time,
    String? orderStatus,
    double? rating,
    double? price,
    double? size,
    double? discount,
    double? flOz,
    double? cbd,
    double? tac,
    double? thc,
    double? totalThc,
    double? totalCbd,
    double? ml,
    double? calories,
    double? strainLimit,
    double? concentratesLimit,
    int? comment,
    int? quantity,
    bool? isSativa,
    bool? isIndica,
    bool? isHybrid,
    bool? isCBD,
    List<String>? images,
    List<String>? transparentImages,
    List<double>? priceList,
    List<double>? sizeList,
    List<String>? tagList,
    List<String>? extractionMethodList,
  }) {
    return Product(
      title: title ?? this.title,
      tag: tag ?? this.tag,
      description: description ?? this.description,
      product: product ?? this.product,
      brand: brand ?? this.brand,
      type: type ?? this.type,
      apparelSize: apparelSize ?? this.apparelSize,
      pack: pack ?? this.pack,
      time: time ?? this.time,
      orderStatus: orderStatus ?? this.orderStatus,
      rating: rating ?? this.rating,
      price: price ?? this.price,
      size: size ?? this.size,
      discount: discount ?? this.discount,
      flOz: flOz ?? this.flOz,
      cbd: cbd ?? this.cbd,
      tac: tac ?? this.tac,
      thc: thc ?? this.thc,
      totalThc: totalThc ?? this.totalThc,
      totalCbd: totalCbd ?? this.totalCbd,
      ml: ml ?? this.ml,
      calories: calories ?? this.calories,
      strainLimit: strainLimit ?? this.strainLimit,
      concentratesLimit: concentratesLimit ?? this.concentratesLimit,
      comment: comment ?? this.comment,
      quantity: quantity ?? this.quantity,
      isSativa: isSativa ?? this.isSativa,
      isIndica: isIndica ?? this.isIndica,
      isHybrid: isHybrid ?? this.isHybrid,
      isCBD: isCBD ?? this.isCBD,
      images: images ?? this.images,
      transparentImages: transparentImages ?? this.transparentImages,
      priceList: priceList ?? this.priceList,
      sizeList: sizeList ?? this.sizeList,
      tagList: tagList ?? this.tagList,
      extractionMethodList: extractionMethodList ?? this.extractionMethodList,
    );
  }
}

List<Product> flowersProducts = [
  Product(
      product: 'flower',
      tag: 'fl0',
      tagList: ['fl0', 'fl0-2', 'fl0-3'],
      images: ["assets/buds/bud1.png", "assets/buds/bud_in_jar/jar1.png"],
      title: "Ice Fog",
      brand: 'House Plant',
      price: 65,
      sizeList: [3.5, 7, 14],
      priceList: [65, 110, 180],
      size: 3.5,
      rating: 4.1,
      thc: 34.4,
      type: 'Flower',
      description:
      'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 30),
  Product(
      product: 'flower',
      tag: 'fl2',
      tagList: ['fl2', 'fl2-2'],
      images: ["assets/buds/bud2.png", "assets/buds/bud_in_jar/jar2.png"],
      title: "White Walker OG",
      brand: 'Henry’s Original',
      price: 40,
      size: 3.5,
      sizeList: [3.5, 14],
      priceList: [40, 120],
      rating: 4.1,
      thc: 29.1,
      cbd: 0.7,
      type: 'Flower',
      description:
      'White Walker OG is an award-winning cannabis variety descended from OG Kush and a mysterious second strain. The cultivar features a pungent, fuel-like flavor with layers of citrusy lemon. A toke of White Walker OG relieves physical tension with a warm, fuzzy blanket of euphoria that both soothes and amplifies the senses. CBX’ White Walker OG is a knockout west coast strain with compact, golf-ball-shaped nuggets that exude pungent fuel-like aromas. This OG Kush descendent has won many awards, including 1st place at multiple High Times Cannabis Cups. White Walker OG’s lemony flavors deliver fast and powerful waves of euphoric relaxation, making it the perfect complement to wind down a user’s day.',
      comment: 55,
      isIndica: true,
      stockPieces: 50),
  Product(
      product: 'flower',
      tag: 'fl3',
      tagList: ['fl3', 'fl3-2'],
      images: ["assets/buds/bud3.png", "assets/buds/bud_in_jar/jar3.png"],
      title: "Grapes N Cream",
      brand: 'Henry’s Original',
      price: 90,
      size: 14,
      sizeList: [14, 28],
      priceList: [90, 160],
      rating: 4.1,
      thc: 32.2,
      cbd: 0.7,
      type: 'Flower',
      description:
      'Smoking Grapes and Cream produces creative effects that stimulate your mind while leaving your body relaxed and prepped for sleep. This strain is ideal for late afternoon or evening hours and pairs best with projects that require creative thinking. Grapes and Cream features a grape flavor profile with surprising notes of pear and vanilla shining through. Our flower has been properly cured and carefully hand-trimmed before being sealed, for the highest level of freshness. We package our flower soon after trimming to retain its fresh flavor and aroma.',
      comment: 55,
      isHybrid: true,
      stockPieces: 36),
  Product(
      product: 'flower',
      tag: 'fl4',
      tagList: ['fl4'],
      images: ["assets/buds/bud4.png", "assets/buds/bud_in_jar/jar4.png"],
      title: "Cherry Dosi",
      brand: 'Aster Farms',
      price: 100,
      size: 14,
      sizeList: [14],
      priceList: [100],
      rating: 4.1,
      thc: 26.1,
      cbd: 0.7,
      type: 'Flower',
      description:
      'Aster Farms Cherry Dosi is a cross of Phantom Cookies and Dosidos, offering up a tingly body high and creative euphoria that\'s great for noon use. This beautiful greenhouse-grown cultivar gives off a cherry-lime aroma with spicy-earthy undertones.',
      comment: 55,
      isSativa: true,
      stockPieces: 42),
  Product(
      product: 'flower',
      tag: 'flw1',
      tagList: ['flw1', 'flw1-2'],
      images: ["assets/buds/bud5.png", "assets/buds/bud_in_jar/jar5.png"],
      title: "The Glove",
      brand: 'Farmer And The Felon',
      size: 3.5,
      price: 50,
      sizeList: [3.5, 7],
      priceList: [50, 100],
      rating: 4.8,
      tac: 25.8,
      thc: 22.1,
      cbd: 0.5,
      comment: 73,
      type: 'Premium',
      isHybrid: true,
      stockPieces: 50,
      description:
      'The Glove is a a cross of Gelato with Biscotti and GSC. The flavor from this cultivar is extremely unique, giving off flavors of cereal, cherry, grapes and gasoline. The Glove is a great choice for an end of day wind down flower. The effects start with a light cerebral shift that turns to an eventual calming, soothing and relaxing experience.'),
  Product(
      product: 'flower',
      tag: 'flw3',
      tagList: ['flw3'],
      images: ["assets/buds/bud6.png", "assets/buds/bud_in_jar/jar5.png"],
      title: "Durban Poison",
      brand: 'Claybourne Co.',
      price: 50,
      size: 3.5,
      sizeList: [3.5],
      priceList: [50],
      rating: 4.1,
      tac: 18,
      thc: 33.5,
      cbd: 0.6,
      comment: 61,
      type: 'Flower',
      description:
      'Durban Poison is the perfect strain to help you stay productive through a busy day, when exploring the outdoors, or to get creative. The buds are round and chunky, and leave a thick coating of trichomes on almost all areas of the plant.',
      isSativa: true,
      stockPieces: 35),
  Product(
      product: 'flower',
      tag: 'flw8',
      tagList: ['flw8', 'flw8-2'],
      images: ["assets/buds/bud7.png", "assets/buds/bud_in_jar/jar4.png"],
      title: "Kush Mints",
      brand: 'Claybourne Co.',
      price: 65,
      size: 3.5,
      sizeList: [3.5, 7],
      priceList: [65, 130],
      type: 'Premium',
      description:
      'Kush Mints is an evenly balanced hybrid strain created through a potent cross of the classic Bubba Kush X Animal Mints strains. Kush Mint brings on well-balanced effects that hit both mind and body with a high level of potency. The aroma is of earthy sweet woods and rich spicy coffee with a heavy kick of mint.',
      rating: 4.1,
      tac: 18,
      thc: 28.7,
      cbd: 0.3,
      comment: 38,
      isHybrid: true,
      stockPieces: 30),
  Product(
      product: 'flower',
      tag: 'flw7',
      tagList: ['flw7', 'flw7-2', 'flw7-3'],
      images: ["assets/buds/bud8.png", "assets/buds/bud_in_jar/jar3.png"],
      title: "Wedding Crasher",
      brand: 'Lime',
      size: 3.5,
      price: 40,
      sizeList: [3.5, 7, 14],
      priceList: [40, 65, 100],
      type: 'Popcorn',
      description:
      'Lime Wedding Crasher is a indica dominant hybrid strain created through a potent cross of the classic Wedding Crasher X Black Lime Bubba strains. You\'d better be prepared for a super long-lasting and stoney high that will relax your body and mind. You\'ll feel a lift at the onset of the high, immediately slamming into your mind with a sense of happiness and motivation. You\'ll be infused with a sense of creative energy and focus that has you feeling laser-sharp with mental clarity that replaces any negative feelings or racing thoughts.',
      rating: 3.8,
      thc: 28.3,
      cbd: 0.3,
      comment: 32,
      isIndica: true,
      stockPieces: 50),
  Product(
      product: 'flower',
      tag: 'flw4',
      tagList: ['flw4', 'flw4-2'],
      images: ["assets/buds/bud9.png", "assets/buds/bud_in_jar/jar2.png"],
      title: "Tahoe",
      brand: 'Almora Farm',
      price: 40,
      sizeList: [3.5, 14],
      priceList: [40, 110],
      size: 3.5,
      description:
      'An astonishing phenotype of OG Kush, Tahoe OG is a tasty bud packing a lemony, earthy punch. Make sure it\'s the end of the day before toking on Tahoe OG, as the strain is known for its sleepy effects.',
      rating: 4.1,
      comment: 43,
      thc: 28.3,
      cbd: 0.5,
      type: 'Flower',
      isIndica: true,
      stockPieces: 40),
  Product(
      product: 'flower',
      tag: 'flw5',
      tagList: ['flw5'],
      images: ["assets/buds/bud10.png", "assets/buds/bud_in_jar/jar1.png"],
      title: "Truffle Souffle",
      brand: 'Maven',
      price: 45,
      size: 3.5,
      sizeList: [3.5],
      priceList: [45],
      description:
      'Orange Truffle Souffle, a cross between Garlic Butter and our very own fan-favorite, Orange Julius, is a true sativa that is sure to enhance any daytime experience. Its nugs are a pale green with hints of plum, wiry orange stigmas and a layer of trichomes so dense that these flowers appear to be covered in clusters of crystals. The initial aroma is sweet and citrus-forward with those fresh fruity notes intensifying upon breaking the nugs apart. Its flavor profile enhances these notes even further with strong pine and orange on the inhale, and a woodsy, earthy exhalation. The nose and flavors of this strain work together to create a bold and refreshing experience for the senses.',
      rating: 4.1,
      tac: 21,
      thc: 32.1,
      comment: 60,
      isSativa: true,
      type: 'Flower',
      stockPieces: 45),
  Product(
      product: 'flower',
      tag: 'flw6',
      tagList: ['flw6'],
      images: [
        "assets/buds/bud11.png",
        "assets/buds/bud3.png",
      ],
      title: "Chomp Smalls",
      brand: 'Wonderbrett',
      price: 35,
      description:
      'CHOMP is the latest collaboration in the Wonderbrett collection, an exclusive new strain developed in partnership with musical superstar RUSS. CHOMP was born and bred from a desire to produce a beautifully complex terpene profile with effects that facilitate the highest levels of artistic creation. The flavor of this captivating cross leans toward the rich, doughy Cookies & Cream lineage, complemented by the sweet taste of zkittlez from Wonderbrett?s legendary OZ Kush. The unique aroma fills the room with notes of subtle gas and citrus candy hovering over delicious hints of chocolate, cinnamon and mint.',
      rating: 4.8,
      size: 3.5,
      sizeList: [3.5],
      priceList: [35],
      tac: 25.8,
      thc: 26.1,
      cbd: 0.7,
      comment: 55,
      type: 'Shake',
      isHybrid: true,
      stockPieces: 25),
  Product(
      product: 'flower',
      tag: 'flw9',
      tagList: ['flw9'],
      images: [
        "assets/buds/bud12.png",
        "assets/buds/bud2.png",
      ],
      title: "Pacific Chemistry Fogg",
      brand: 'Fog City Farms',
      size: 7,
      price: 75,
      sizeList: [7],
      priceList: [75],
      type: 'Flower',
      description:
      'Our Foggies premium smalls come in a 7g bag. No shake, same high quality flower as in our jars...just smaller nugs. This powerful strain can bring relaxation as well as open up your creative, artistic senses. It has earthy fuel notes with a sweet and sour floral backend. Pacific Chemistry is the cousin of Fog City’s staple, Pacific Gas, also being fuel forward but with a sour addition that adds a more buzzy mental stimulation to its effects.',
      rating: 4.1,
      comment: 28,
      thc: 39.6,
      isHybrid: true,
      stockPieces: 21),
  Product(
      product: 'flower',
      tag: 'flw10',
      tagList: ['flw10', 'flw10-2'],
      images: [
        "assets/buds/bud13.png",
        "assets/buds/bud1.png",
      ],
      title: "Hybrid Kief",
      brand: 'Claybtourne Co.',
      price: 60,
      type: 'Flower',
      size: 4,
      sizeList: [4, 8],
      priceList: [60, 100],
      description:
      'Inside each and every Power Pack is an 1/8th of small buds, 1g jar of kief, and a special handy dandy kief shovel - all in one convenient rolling pouch. Enjoy the versatility of the claybourne power pack: use the flower only, smoke a kief bowl, add a kief topper, infuse pre-rolls. Create your own experience with the power of kief!',
      rating: 4.1,
      tac: 21,
      thc: 29.2,
      cbd: 0.7,
      comment: 33,
      isHybrid: true,
      stockPieces: 40),
];
List<Product> preRollProducts = [
  Product(
      product: 'preRoll',
      tag: 'pre6',
      images: ["assets/preRoll/pre1.png"],
      title: "Drift Mini",
      brand: 'Weekenders',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      size: 3.5,
      price: 35,
      comment: 19,
      pack: '7pk',
      thc: 19.7,
      cbd: 2.8,
      isHybrid: true,
      type: 'PreRolls',
      stockPieces: 100),
  Product(
      product: 'preRoll',
      tag: 'pre7',
      images: ["assets/preRoll/pre2.png"],
      title: "Bacio Gelato Mini",
      brand: 'West Coast Cure',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      size: 3,
      price: 30,
      pack: '6pk',
      thc: 28.4,
      cbd: 0.2,
      comment: 32,
      isIndica: true,
      type: 'PreRolls',
      stockPieces: 110),
  Product(
      product: 'preRoll',
      tag: 'pre8',
      images: ["assets/preRoll/pre3.png"],
      title: "Tangie Mini",
      brand: 'West Coast Cure',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      size: 3,
      price: 30,
      comment: 9,
      pack: '6pk',
      thc: 28.1,
      cbd: 0.2,
      isSativa: true,
      type: 'PreRolls',
      stockPieces: 70),
  Product(
      product: 'preRoll',
      tag: 'pre9',
      images: ["assets/preRoll/pre4.png"],
      title: "Bubble Gum",
      brand: 'Henry\'s Original',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      size: 2,
      price: 30,
      comment: 15,
      pack: '4pk',
      thc: 26.9,
      isIndica: true,
      type: 'PreRolls',
      stockPieces: 50),
  Product(
      product: 'preRoll',
      tag: 'pre10',
      images: ["assets/preRoll/pre5.png"],
      title: "Durban Poison",
      brand: 'Jeeter',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      size: 2.5,
      price: 35,
      pack: '5pk',
      comment: 21,
      thc: 38.8,
      isSativa: true,
      type: 'PreRolls',
      stockPieces: 100),
  Product(
      product: 'preRoll',
      tag: 'pre1',
      images: ["assets/preRoll/pre6.png"],
      title: "Coast CBD 4 Pack Preroll",
      brand: 'Henry\'s Original',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      size: 2,
      price: 30,
      comment: 25,
      thc: 1.4,
      cbd: 26.9,
      isCBD: true,
      type: 'PreRolls',
      stockPieces: 80),
  Product(
      product: 'preRoll',
      tag: 'pre2',
      images: [
        "assets/preRoll/pre7.png",
      ],
      title: "Berry Tart",
      brand: 'Swift Lifts',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      size: 2.5,
      price: 45,
      comment: 11,
      pack: '5pk',
      thc: 41.8,
      cbd: 0.5,
      isIndica: true,
      type: 'Infused',
      stockPieces: 60),
  Product(
      product: 'preRoll',
      tag: 'pre3',
      images: ["assets/preRoll/pre8.png"],
      title: "The Social Sativa Blend",
      brand: 'Lowell Farms',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      price: 55,
      size: 3.5,
      comment: 9,
      pack: '6pk',
      thc: 29.5,
      cbd: 0.4,
      isSativa: true,
      type: 'PreRolls',
      stockPieces: 90),
  Product(
      product: 'preRoll',
      tag: 'pre4',
      images: ["assets/preRoll/pre9.png"],
      title: "Bogeyman Preroll",
      brand: 'Slims',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      price: 16,
      size: 1,
      comment: 19,
      thc: 28.1,
      cbd: 0.2,
      isHybrid: true,
      type: 'PreRolls',
      stockPieces: 82),
  Product(
      product: 'preRoll',
      tag: 'pre5',
      images: ["assets/preRoll/pre10.png"],
      title: "Butterstuff Preroll",
      brand: 'Ozone',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      size: 1,
      price: 16,
      comment: 19,
      thc: 28.1,
      cbd: 0.2,
      isSativa: true,
      type: 'PreRolls',
      stockPieces: 47),
];
List<Product> concentratesProducts = [
  Product(
      product: 'concentrate',
      tag: 'ext1',
      images: [
        "assets/concentrates/grassroots_lil_sebastian_con.png",
      ],
      transparentImages: [
        "assets/concentrates/grassroots_lil_sebastian_con.png",
      ],
      title: "Lil Sebastian",
      brand: 'Grassroots',
      rating: 4.1,
      size: 1,
      price: 60,
      comment: 25,
      thc: 72,
      cbd: 0.1,
      isHybrid: true,
      type: 'Live Budder',
      extractionMethodList: ['Live'],
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      stockPieces: 61),
  Product(
      product: 'concentrate',
      tag: 'ext2',
      images: [
        "assets/concentrates/amigo_ghost_hulk.png",
      ],
      transparentImages: [
        "assets/concentrates/amigo_ghost_hulk.png",
      ],
      title: "Ghost Hulk ",
      brand: 'Amigo',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      size: 1,
      comment: 18,
      price: 55,
      thc: 79,
      isHybrid: true,
      type: 'Live Sugar',
      extractionMethodList: ['Live'],
      stockPieces: 93),
  Product(
      product: 'concentrate',
      tag: 'ext3',
      images: [
        "assets/concentrates/budderfly_sweet_og.png",
      ],
      transparentImages: [
        "assets/concentrates/budderfly_sweet_og.png",
      ],
      title: "Sweet OG",
      brand: 'Budderfly',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      size: 1,
      price: 50,
      comment: 27,
      thc: 75,
      isHybrid: true,
      extractionMethodList: ['Solventless'],
      type: 'Live Sugar',
      stockPieces: 48),
  Product(
      product: 'concentrate',
      tag: 'ext4',
      images: [
        "assets/concentrates/22k_blue_dream.png",
      ],
      transparentImages: [
        "assets/concentrates/22k_blue_dream.png",
      ],
      title: "Blue Dream",
      brand: '22K',
      rating: 4.1,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      size: 1,
      price: 55,
      comment: 21,
      isSativa: true,
      thc: 71,
      type: 'Live Budder',
      extractionMethodList: ['Live'],
      stockPieces: 28),
  Product(
      product: 'concentrate',
      tag: 'ext5',
      images: [
        "assets/concentrates/west_cost_blue_lava.png",
      ],
      transparentImages: [
        "assets/concentrates/west_cost_blue_lava.png",
      ],
      title: "Blue Lava",
      brand: 'Rythm',
      rating: 4.1,
      comment: 55,
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      size: 1,
      price: 25,
      thc: 74,
      isIndica: true,
      type: 'Live Sugar',
      extractionMethodList: ['Live'],
      stockPieces: 76),
  Product(
      product: 'concentrate',
      tag: 'ext6',
      images: [
        "assets/concentrates/jetty_extracts_guava_gas.png",
      ],
      transparentImages: [
        "assets/concentrates/jetty_extracts_guava_gas.png",
      ],
      title: "Ghost OG",
      brand: 'Budderfly',
      description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
      rating: 4.1,
      comment: 13,
      size: 1,
      price: 65,
      thc: 74,
      isIndica: true,
      type: 'Live Sugar',
      extractionMethodList: ['Solventless'],
      stockPieces: 68),
  Product(
    product: 'concentrate',
    tag: 'ext7',
    images: [
      "assets/concentrates/west_coast_peach_rings.png",
    ],
    transparentImages: [
      "assets/concentrates/west_coast_peach_rings.png",
    ],
    title: "Peach Rings Badder",
    brand: 'Verano',
    rating: 4.1,
    price: 60,
    size: 1,
    comment: 27,
    thc: 74,
    type: 'Live Rosin',
    description:
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
    isHybrid: true,
    extractionMethodList: ['Solventless'],
    stockPieces: 50,
  ),
  Product(
    product: 'concentrate',
    tag: 'ext8',
    images: [
      "assets/concentrates/west_cost_pink_cookies.png",
    ],
    transparentImages: [
      "assets/concentrates/west_cost_pink_cookies.png",
    ],
    title: "Pink Cookies Sugar",
    brand: 'Ozone Reserve',
    rating: 4.1,
    price: 60,
    size: 1,
    comment: 16,
    thc: 74,
    type: 'Live Rosin',
    isSativa: true,
    stockPieces: 70,
    extractionMethodList: ['Solventless'],
    description:
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
  ),
  Product(
    product: 'concentrate',
    tag: 'ext9',
    images: [
      "assets/concentrates/west_cost_sour_lemon.png",
    ],
    transparentImages: [
      "assets/concentrates/west_cost_sour_lemon.png",
    ],
    title: "Sour Lemon Sauce",
    size: 1,
    brand: 'FloraCal',
    rating: 4.1,
    price: 60,
    comment: 5,
    thc: 74,
    isSativa: true,
    type: 'Live Rosin',
    extractionMethodList: ['Live'],
    stockPieces: 33,
    description:
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
  ),
  Product(
    product: 'concentrate',
    tag: 'ext10',
    images: [
      "assets/concentrates/west_cost_sour_lemon.png",
    ],
    transparentImages: [
      "assets/concentrates/west_cost_sour_lemon.png",
    ],
    title: "Guava Gas",
    brand: 'Jetty Extracts',
    rating: 4.1,
    size: 1,
    price: 65,
    comment: 15,
    thc: 74,
    type: 'Live Rosin',
    isIndica: true,
    extractionMethodList: ['Solventless'],
    stockPieces: 19,
    description:
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ',
  )
];
List<Product> vaporizersProducts = [
  Product(
      product: 'vaporizers',
      tag: 'vap1',
      images: ["assets/vaporizers/v1.png"],
      title: "Do-Si-Dos Original",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 0.5,
      price: 45,
      thc: 74,
      isHybrid: true,
      type: 'Cartridge',
      description: AppStrings.loremIpsum,
      stockPieces: 12),
  Product(
      product: 'vaporizers',
      tag: 'vap2',
      images: ["assets/vaporizers/v2.png"],
      title: "Skywalker OG",
      brand: 'Stiiizy',
      rating: 4.1,
      price: 45,
      size: 0.5,
      thc: 79,
      isIndica: true,
      description: AppStrings.loremIpsum,
      type: 'Cartridge',
      cbd: 0.1,
      stockPieces: 28),
  Product(
      product: 'vaporizers',
      tag: 'vap3',
      images: ["assets/vaporizers/v3.png"],
      title: "Strawberry Cough",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 0.5,
      price: 40,
      thc: 75,
      isSativa: true,
      type: 'Cartridge',
      description: AppStrings.loremIpsum,
      stockPieces: 52),
  Product(
      product: 'vaporizers',
      tag: 'vap4',
      images: ["assets/vaporizers/v4.png"],
      title: "Gelato",
      brand: 'Stiiizy',
      rating: 4.1,
      price: 50,
      size: 0.5,
      isHybrid: true,
      thc: 71,
      cbd: 0.1,
      type: 'Cartridge',
      description: AppStrings.loremIpsum,
      stockPieces: 26),
  Product(
      product: 'vaporizers',
      tag: 'vap5',
      images: ["assets/vaporizers/v5.png"],
      title: "Blue Burst",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 0.5,
      price: 50,
      thc: 74,
      isHybrid: true,
      type: 'Cartridge',
      description: AppStrings.loremIpsum,
      stockPieces: 62),
  Product(
      product: 'vaporizers',
      tag: 'vap6',
      images: ["assets/vaporizers/v6.png"],
      title: "Do-Si-Dos Original",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 1,
      price: 70,
      thc: 74,
      isIndica: true,
      type: 'Cartridge',
      description: AppStrings.loremIpsum,
      stockPieces: 33),
  Product(
      product: 'vaporizers',
      tag: 'vap7',
      images: ["assets/vaporizers/v7.png"],
      title: "OG Kush",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 0.5,
      price: 50,
      thc: 74,
      isIndica: true,
      type: 'Cartridge',
      stockPieces: 29,
      description: AppStrings.loremIpsum),
  Product(
      product: 'vaporizers',
      tag: 'vap8',
      images: ["assets/vaporizers/v8.png"],
      title: "Birthday Cake",
      brand: 'Stiiizy',
      rating: 4.1,
      price: 45,
      size: 0.5,
      thc: 74,
      isHybrid: true,
      type: 'Cartridge',
      stockPieces: 51,
      description: AppStrings.loremIpsum),
  Product(
      product: 'vaporizers',
      tag: 'vap9',
      images: ["assets/vaporizers/v9.png"],
      title: "Juicy Melon",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 1,
      price: 75,
      thc: 74,
      isHybrid: true,
      type: 'Cartridge',
      stockPieces: 19,
      description:
      "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'vaporizers',
      tag: 'vap10',
      images: ["assets/vaporizers/v10.png"],
      title: "Granddaddy Purp",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 0.5,
      price: 45,
      thc: 74,
      isHybrid: true,
      type: 'Cartridge',
      stockPieces: 100,
      description: AppStrings.loremIpsum),
];
List<Product> ediblesProducts = [
  Product(
      product: 'edibles',
      tag: 'ed1',
      images: ["assets/edibles/e1.png"],
      transparentImages: ["assets/edibles/e1.png"],
      title: "1:1 Lush Black Cherry",
      brand: 'Mindy\'s',
      rating: 4.1,
      pack: '20ct',
      price: 30,
      thc: 100,
      cbd: 100,
      isHybrid: true,
      type: 'Gummy',
      description:
      'p.THC: 720mg | p.Limonene: 13.43mg/g | p.Linalool: 4.25mg/g | p.CBD: 1.35mg',
      stockPieces: 30),
  Product(
      product: 'edibles',
      tag: 'ed2',
      images: ["assets/edibles/e2.png"],
      transparentImages: ["assets/edibles/e2.png"],
      title: "1:1 Orchard Peach",
      brand: 'Camino',
      rating: 4.1,
      pack: '10ct',
      price: 30,
      thc: 100,
      cbd: 100,
      type: 'Gummy',
      isHybrid: true,
      stockPieces: 45),
  Product(
      product: 'edibles',
      tag: 'ed3',
      images: ["assets/edibles/e3.png"],
      transparentImages: ["assets/edibles/e3.png"],
      title: "10:1 Strawberry",
      brand: 'Wana',
      rating: 4.1,
      price: 25,
      pack: '10ct',
      thc: 10,
      cbd: 100,
      type: 'Gummy',
      isCBD: true,
      description: 'BUDDERFLY - SWEET OG SAUCE 0.5G',
      stockPieces: 90),
  Product(
      product: 'edibles',
      tag: 'ed4',
      images: ["assets/edibles/e4.png"],
      transparentImages: ["assets/edibles/e4.png"],
      title: "Milk Chocolate Peanut Brittle",
      brand: 'Mindy\'s',
      rating: 4.1,
      pack: '10ct',
      price: 25,
      isHybrid: true,
      thc: 100,
      type: 'Chocolate',
      description: '22 K - BLUE DREAM LIVE RESIN DIAMONDS 1G',
      stockPieces: 50),
  Product(
      product: 'edibles',
      tag: 'ed5',
      images: ["assets/edibles/e5.png"],
      transparentImages: ["assets/edibles/e5.png"],
      title: "Mint Cookie Milk Chocolate",
      brand: 'Nature\'s Grace',
      rating: 4.1,
      pack: '10ct',
      price: 20,
      thc: 100,
      isHybrid: true,
      type: 'Chocolate',
      description: 'WEST COAST - BLUE LAVA 1G SHATTER',
      stockPieces: 50),
  Product(
      product: 'edibles',
      tag: 'ed6',
      images: ["assets/edibles/e6.png"],
      transparentImages: ["assets/edibles/e6.png"],
      title: "Wintermint Mints",
      brand: 'Encore',
      rating: 4.1,
      pack: '20ct',
      price: 20,
      thc: 100,
      isHybrid: true,
      type: 'Mint',
      stockPieces: 13),
  Product(
      product: 'edibles',
      tag: 'ed7',
      images: ["assets/edibles/e7.png"],
      transparentImages: ["assets/edibles/e7.png"],
      title: "1:1 Tangerine Mints",
      brand: 'Encore',
      rating: 4.1,
      price: 20,
      pack: '20ct',
      thc: 100,
      cbd: 100,
      isCBD: true,
      type: 'Mint',
      stockPieces: 100,
      description:
      "each Rings Live Resin Badder from WCC is an Indica-dominant concentrate that’s packed with copious amounts of THC and a loud fruit flavor. The effects from these dabs produce a strong, euphoric high that generates a relaxing and tranquil mindset. With a gassed-up peachy exhale, this live resin badder provides comfort for the distressed high-tolerance consumer."),
  Product(
      product: 'edibles',
      tag: 'ed8',
      images: ["assets/edibles/e8.png"],
      transparentImages: ["assets/edibles/e8.png"],
      title: "Sours Watermelon Spritz",
      brand: 'Camino',
      rating: 4.1,
      pack: '10ct',
      price: 30,
      thc: 100,
      isHybrid: true,
      type: 'Gummy',
      stockPieces: 23,
      description:
      "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'edibles',
      tag: 'ed9',
      images: ["assets/edibles/e9.png"],
      transparentImages: ["assets/edibles/e9.png"],
      title: "Juicy Melon 1:1 ",
      brand: 'Mindy\'s ',
      rating: 4.1,
      pack: '20ct',
      price: 30,
      thc: 100,
      type: 'Gummy',
      isHybrid: true,
      stockPieces: 50,
      description:
      "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'edibles',
      tag: 'ed10',
      images: ["assets/edibles/e10.png"],
      transparentImages: ["assets/edibles/e10.png"],
      title: "Live Resin Raspberry",
      brand: 'Lost Farm',
      rating: 4.1,
      pack: '10ct',
      price: 32,
      thc: 100,
      isSativa: true,
      type: 'Gummy',
      stockPieces: 18,
      description:
      "Jetty Live Rosin is grown using organic methods on the sun-soaked Jetty Farm. Whole plant cannabis, harvested at the peak of ripeness then immediately frozen on site. Extracted entirely without chemicals, using just ice, water, heat and pressure. This is premium-grade, 90μ Jetty Live Rosin. Jetty takes the craft approach to concentrates with small batches made from premium fresh frozen cannabis. We aim for big flavor and broad terpene profiles, and never start out with a set menu. That means a variety of concentrate types like rosin, badder, sauce, sugar or diamonds, and quantities that may be limited.")
];
List<Product> beveragesProducts = [
  Product(
      product: 'beverages',
      tag: 'b1',
      images: ["assets/beverages/b1.png"],
      title: "Sparkling Sauvage 2019",
      brand: 'Rebel Coast',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 49,
      price: 30,
      thc: 10,
      type: 'Sparkling',
      stockPieces: 45,
      description:
      'Rebel Coast started producing traditional wine in 2012, and then revolutionized the cannabis industry in 2017 with the introduction of a sauvignon blanc cannabis-infused beverage, offering a delicious, low-calorie alcohol alternative to a new generation of consumers. Born and bred in California, our beverages are designed for the rebellious spirit to celebrate the best moments in life.'),
  Product(
      product: 'beverages',
      tag: 'b1',
      images: ["assets/beverages/b2.png"],
      title: "Lemon Lime",
      brand: 'Rebel Coast',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 0,
      price: 30,
      thc: 10,
      type: 'Seltzer',
      stockPieces: 35,
      description:
      'Rebel Coast started producing traditional wine in 2012, and then revolutionized the cannabis industry in 2017 with the introduction of a sauvignon blanc cannabis-infused beverage, offering a delicious, low-calorie alcohol alternative to a new generation of consumers. Born and bred in California, our beverages are designed for the rebellious spirit to celebrate the best moments in life.'),
  Product(
      product: 'beverages',
      tag: 'b1',
      images: ["assets/beverages/b3.png"],
      title: "Pink Passion",
      brand: 'Rebel Coast',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 49,
      price: 30,
      thc: 10,
      type: 'Sparkling',
      stockPieces: 18,
      description:
      'Rebel Coast started producing traditional wine in 2012, and then revolutionized the cannabis industry in 2017 with the introduction of a sauvignon blanc cannabis-infused beverage, offering a delicious, low-calorie alcohol alternative to a new generation of consumers. Born and bred in California, our beverages are designed for the rebellious spirit to celebrate the best moments in life.'),
  Product(
      product: 'beverages',
      tag: 'b11',
      images: ["assets/beverages/b11.png"],
      title: "Lemon Lavender",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 24,
      thc: 5,
      type: 'Tonic',
      stockPieces: 120,
      description:
      'Call it a double – with 5mg of THC, these Hi Boys have 2.5x the THC of our standard Canns. Smooth and unexpected, Lemon Lavender is a fan favorite. Designed for fun, it’s a tasty delight that will leave you feeling great. Whether you’re sipping one or downing several, these Canns will make you feel light and happy – no hangover ever. 5mg of THC in each can'),
  Product(
      product: 'beverages',
      tag: 'b12',
      images: ["assets/beverages/b12.png"],
      title: "Ginger Lemongrass",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 24,
      type: 'Tonic',
      thc: 5,
      stockPieces: 12,
      description:
      'Winter? I hardly know her. Zesty and smooth, this Spring Seasonal flavor was crafted to give you a little spring in your step. With no hangover, all-natural ingredients, and only 35 calories per can, Ginger Lemongrass will transport you to that spring fever state of mind.'),
  Product(
      product: 'beverages',
      tag: 'b13',
      images: ["assets/beverages/b13.png"],
      title: "Blood Orange Cardamom",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 24,
      type: 'Tonic',
      thc: 5,
      stockPieces: 32,
      description:
      'Call it a double – with 5mg of THC, these Hi Boys have 2.5x the THC of our standard Canns. Juicy and bright, Blood Orange Cardamom is a lightly spiced treat that doesn’t disappoint. Designed for fun, it’s a tasty delight that will leave you feeling great. Whether you’re sipping one or downing several, these Canns will make you feel light and happy – no hangover ever. 5mg of THC in each can'),
  Product(
      product: 'beverages',
      tag: 'b4',
      images: ["assets/beverages/b4.png"],
      title: "The Big Game Starter Pack",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 75,
      type: 'Tonic',
      thc: 5,
      stockPieces: 26,
      description:
      'Thirsty for something different? Grab our new Starter Pack and see why Cann is the best thing to happen to drinking since drinking. Discover your favorite flavor with this limited-edition bundle.\n\n\nBundle includes:\n\nOne 6 Pack of Blood Orange Cardamom.\nOne 6 Pack of Grapefruit Rosemary.\nOne 6 Pack of Lemon Lavender'),
  Product(
      product: 'beverages',
      tag: 'b5',
      images: ["assets/beverages/b5.png"],
      title: "The Big Bang Pack",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 216,
      type: 'Tonic',
      thc: 5,
      stockPieces: 19,
      description:
      'Thirsty for something different? Grab our new Starter Pack and see why Cann is the best thing to happen to drinking since drinking. Discover your favorite flavor with this limited-edition bundle.\n\n\nBundle includes:\n\nOne 6 pack of Blood Orange Cardamom.\nOne 4 pack of Blood Orange Cardamom Hi Boys.One 8 pack of Blood Orange Cardamom Roadies.\nOne 6 pack of Lemon Lavender.\nOne 4 pack of Lemon Lavender Hi Boys.\nOne 8 pack of Lemon Lavender Roadies.\nOne 6 pack of Grapefruit Rosemary.\nOne 4 pack of Grapefruit Rosemary Hi Boys.\nOne 8 pack of Grapefruit Rosemary Roadies')
];
List<Product> topicalsProducts = [
  Product(
      product: 'topicals',
      tag: 'to2',
      images: ["assets/topicals/t2.png"],
      title: "Fire & Ice | 1:1 Roll On",
      brand: 'Buddies',
      rating: 4.1,
      price: 33,
      thc: 250,
      cbd: 250,
      type: 'Lotion',
      stockPieces: 17),
  Product(
      product: 'topicals',
      tag: 'to3',
      images: ["assets/topicals/t3.png"],
      title: "1:1 Pain Relief Lotion",
      brand: 'Avexia',
      rating: 4.1,
      price: 50,
      thc: 100,
      cbd: 100,
      type: 'Lotion',
      stockPieces: 19),
  Product(
      product: 'topicals',
      tag: 'to4',
      images: ["assets/topicals/t4.png"],
      title: "1:1 Pain Relief Balm",
      brand: 'Avexia',
      rating: 4.1,
      price: 45,
      thc: 100,
      cbd: 100,
      type: 'Balm',
      stockPieces: 20),
  Product(
      product: 'topicals',
      tag: 'to5',
      images: ["assets/topicals/t5.png"],
      title: "2:1 Body Oil",
      brand: 'Pure Essentials',
      rating: 4.1,
      price: 30,
      thc: 100,
      cbd: 200,
      type: 'Body Oil',
      stockPieces: 17),
  Product(
      product: 'topicals',
      tag: 'to6',
      images: ["assets/topicals/t6.png"],
      title: "Plain Jane",
      brand: 'High Gorgeous',
      rating: 4.1,
      price: 30,
      cbd: 20,
      totalCbd: 500,
      type: 'Lotion',
      isCBD: true,
      stockPieces: 22),
];
List<Product> tincturesProducts = [
  Product(
      product: 'tinctures',
      tag: 'tin1',
      images: ["assets/tinctures/t1.png"],
      title: "Drift Away",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 30,
      totalThc: 300,
      thc: 300,
      ml: 30,
      flOz: 1,
      isIndica: true,
      type: 'Dropper',
      stockPieces: 20),
  Product(
      product: 'tinctures',
      tag: 'tin2',
      images: ["assets/tinctures/t2.png"],
      title: "CBD 4:1",
      brand: 'Care by Design',
      rating: 4.1,
      price: 42,
      totalThc: 300,
      thc: 60,
      cbd: 240,
      ml: 15,
      flOz: 0.5,
      type: 'Dropper',
      stockPieces: 28),
  Product(
      product: 'tinctures',
      tag: 'tin3',
      images: ["assets/tinctures/t3.png"],
      title: "CBD 2:1",
      brand: 'Care by Design',
      rating: 4.1,
      price: 42,
      totalThc: 300,
      thc: 120,
      cbd: 240,
      ml: 15,
      flOz: 0.5,
      type: 'Dropper',
      stockPieces: 15),
  Product(
      product: 'tinctures',
      tag: 'tin4',
      images: ["assets/tinctures/t4.png"],
      title: "Lights Out",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 50,
      totalThc: 1000,
      thc: 1000,
      ml: 30,
      flOz: 1,
      isIndica: true,
      type: 'Dropper',
      stockPieces: 19),
  Product(
      product: 'tinctures',
      tag: 'tin5',
      images: ["assets/tinctures/t5.png"],
      title: "Mood Magic",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 30,
      totalThc: 300,
      thc: 300,
      ml: 30,
      flOz: 1,
      isHybrid: true,
      type: 'Dropper',
      stockPieces: 23),
  Product(
      product: 'tinctures',
      tag: 'tin6',
      images: ["assets/tinctures/t6.png"],
      title: "Stay Lifted",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 30,
      totalThc: 300,
      thc: 300,
      ml: 30,
      flOz: 1,
      isSativa: true,
      type: 'Dropper',
      stockPieces: 30),
  Product(
      product: 'tinctures',
      tag: 'tin7',
      images: ["assets/tinctures/t7.png"],
      title: "CBD 8:1",
      brand: 'Care by Design',
      rating: 4.1,
      price: 42,
      thc: 30,
      cbd: 240,
      ml: 15,
      flOz: 0.5,
      type: 'Dropper',
      stockPieces: 28),
  Product(
      product: 'tinctures',
      tag: 'tin8',
      images: ["assets/tinctures/t8.png"],
      title: "Wicked Apple",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 60,
      thc: 1000,
      cbd: 1.9,
      ml: 30,
      flOz: 1,
      isHybrid: true,
      type: 'Dropper',
      stockPieces: 21),
];
List<Product> growingProducts = [
  Product(
      product: 'growing',
      tag: 'g1',
      images: ["assets/growing/g1.png"],
      title: "ROI GC-630E",
      brand: 'Grower\'s Choice',
      rating: 4.1,
      price: 699,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g2',
      images: ["assets/growing/g2.png"],
      title: "Master Controller",
      brand: 'Grower\'s Choice',
      rating: 4.1,
      price: 399,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g3',
      images: ["assets/growing/g3.png"],
      title: "SE 315W Lamp Day Light",
      brand: 'Grower\'s Choice',
      rating: 4.1,
      price: 139,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g5',
      images: ["assets/growing/g5.png"],
      title: "Dimmable Led Grow Light",
      brand: 'Optic',
      rating: 4.1,
      price: 219,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g6',
      images: ["assets/growing/g6.png"],
      title: "Infinity Rope Clip Hanger",
      brand: 'AC INFINITY',
      rating: 4.1,
      price: 219,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g7',
      images: ["assets/growing/g7.png"],
      title: "200W Full Spectrum Light",
      brand: 'AC INFINITY',
      rating: 4.1,
      price: 249,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g8',
      images: ["assets/growing/g8.png"],
      title: "PhatSlim 1XL LED Grow Light",
      brand: 'Optic',
      rating: 4.1,
      price: 370,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g9',
      images: ["assets/growing/g9.png"],
      title: "Slim 650S LED Grow Light",
      brand: 'Optic',
      rating: 4.1,
      price: 1099,
      stockPieces: 5),
  Product(
      product: 'growing',
      tag: 'g10',
      images: ["assets/growing/g10.png"],
      title: "Iongrid T24 Full Spectrum",
      brand: 'AC INFINITY',
      rating: 4.1,
      price: 350,
      stockPieces: 5),
];
List<Product> cbdProducts = [
  Product(
      product: 'cbd',
      tag: 'cbd1',
      images: ["assets/cbd/cbd1.jpg"],
      title: "Classic 1:1 CBG:CBD",
      brand: 'Lazarus Naturals',
      rating: 4.1,
      price: 200,
      ml: 120,
      flOz: 4.05,
      type: 'Oil',
      stockPieces: 28),
  Product(
      product: 'cbd',
      tag: 'cbd2',
      images: ["assets/cbd/cbd2.jpg"],
      title: "1:1 CBD/CBG",
      brand: 'SBCBD',
      rating: 4.1,
      price: 50,
      ml: 15,
      flOz: 0.5,
      type: 'Elixir',
      stockPieces: 28),
];
List<Product> accessoriesProducts = [
  Product(
      product: 'accessories',
      tag: 'a1',
      images: ["assets/accessories/a1.png"],
      title: "Unbleached King Sized Cones",
      brand: 'OCB',
      rating: 4.1,
      price: 3,
      type: 'Cones',
      stockPieces: 50),
  Product(
      product: 'accessories',
      tag: 'a2',
      images: ["assets/accessories/a2.png"],
      title: "Grynder",
      brand: 'Stache',
      rating: 4.1,
      price: 35,
      type: 'Grinder',
      stockPieces: 50),
  Product(
      product: 'accessories',
      tag: 'a3',
      images: ["assets/accessories/a3.png"],
      title: "Eyce Silicon Spoon",
      brand: 'Eyce',
      rating: 4.1,
      price: 17,
      type: 'Pipe',
      stockPieces: 10),
  Product(
      product: 'accessories',
      tag: 'a4',
      images: ["assets/accessories/a4.png"],
      title: "Butter MB2e Machine",
      brand: 'Magical',
      rating: 4.1,
      price: 225,
      type: 'Infuser',
      stockPieces: 10),
  Product(
      product: 'accessories',
      tag: 'a5',
      images: ["assets/accessories/a5.png"],
      title: "Terminator Finish Beaker",
      brand: 'Red Eye Tek',
      rating: 4.1,
      price: 82,
      type: 'Bong',
      stockPieces: 10),
  Product(
      product: 'accessories',
      tag: 'a6',
      images: ["assets/accessories/a6.png"],
      title: "Beaker Bong",
      brand: 'Cirrus Glass',
      rating: 4.1,
      price: 90,
      type: 'Bong',
      stockPieces: 10),
  Product(
      product: 'accessories',
      tag: 'a7',
      images: ["assets/accessories/a7.png"],
      title: "24K King Size Rolling Papers",
      brand: 'Shine',
      rating: 4.1,
      price: 10,
      type: 'Papers',
      stockPieces: 50),
  Product(
      product: 'accessories',
      tag: 'a8',
      images: ["assets/accessories/a8.png"],
      title: "Dabber Set",
      brand: 'Lit Silicon',
      rating: 4.1,
      price: 24,
      type: 'Tool',
      stockPieces: 50),
  Product(
      product: 'accessories',
      tag: 'a9',
      images: ["assets/accessories/a9.png"],
      title: "6.5” Concentrate Bubbler",
      brand: 'West Coast Gifts',
      rating: 4.1,
      price: 56,
      type: 'Dab Rig',
      stockPieces: 50),
  Product(
      product: 'accessories',
      tag: 'a10',
      images: ["assets/accessories/a10.png"],
      title: "Duo Vaporizer",
      brand: 'Zenco',
      rating: 4.1,
      price: 250,
      type: 'Vaporizer',
      stockPieces: 5),
];
List<Product> apparelProducts = [
  Product(
      product: 'apparel',
      tag: 'ap1',
      images: ["assets/apparel/ap1.png"],
      title: "Women's T-Shirts",
      brand: 'Brand',
      price: 13,
      apparelSize: 'Size',
      stockPieces: 20),
  Product(
      product: 'apparel',
      tag: 'ap2',
      images: ["assets/apparel/ap2.png"],
      title: "Sweatshirts",
      brand: 'Brand',
      price: 18,
      apparelSize: 'Size',
      stockPieces: 20),
  Product(
      product: 'apparel',
      tag: 'ap3',
      images: ["assets/apparel/ap3.png"],
      title: "Sweatshirts",
      brand: 'Brand',
      price: 25,
      apparelSize: 'Size',
      stockPieces: 20),
  Product(
      product: 'apparel',
      tag: 'ap4',
      images: ["assets/apparel/ap4.png"],
      title: "Sweatshirts",
      brand: 'Brand',
      price: 25,
      apparelSize: 'Size',
      stockPieces: 20),
];
List<Product> storeLastOrders2 = [
  Product(
      product: 'flower',
      tag: 'fl0',
      title: "Ice Fog",
      brand: 'House Plant',
      price: 65,
      size: 3.5,
      quantity: 2,
      time: 'now'),
  Product(
      product: 'edibles',
      tag: 'ed9',
      title: "Juicy Melon 1:1 ",
      brand: 'Mindy\'s ',
      pack: '20ct',
      price: 30,
      quantity: 1,
      time: '20 min ago'),
  Product(
      product: 'vaporizers',
      tag: 'vap9',
      title: "Juicy Melon",
      brand: 'Stiiizy',
      size: 1,
      price: 75,
      quantity: 2,
      time: '29 min ago'),
  Product(
      product: 'flower',
      tag: 'flw9',
      title: "Pacific Chemistry Fogg",
      brand: 'Fog City Farms',
      size: 7,
      price: 75,
      quantity: 1,
      time: '31 min ago'),
  Product(
      product: 'concentrate',
      tag: 'ext10',
      title: "Guava Gas",
      brand: 'Jetty Extracts',
      rating: 4.1,
      size: 1,
      price: 65,
      quantity: 1,
      time: '37 min ago'),
  Product(
      product: 'preRoll',
      tag: 'pre3',
      title: "The Social Sativa Blend",
      brand: 'Lowell Farms',
      price: 55,
      size: 3.5,
      quantity: 3,
      time: '37 min ago'),
  Product(
      product: 'flower',
      tag: 'flw6',
      title: "Chomp Smalls",
      brand: 'Wonderbrett',
      price: 35,
      size: 3.5,
      quantity: 2,
      time: '38 min ago')
];

/// OFFER MODEL
List<Product> offerList = [
  Product(
      product: 'flower',
      tag: 'Ofl1',
      images: ["assets/offer/offer1.png"],
      title: 'Flower Jar',
      brand: 'State Flower',
      price: 45,
      size: 3.5,
      rating: 4.1,
      discount: 50,
      thc: 28.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'Pre-Roll',
      tag: 'Opr1',
      images: ["assets/offer/offer2.png"],
      title: 'Rainbow Belt',
      brand: 'Cali Love',
      price: 55,
      size: 3.5,
      rating: 4.1,
      discount: 20,
      thc: 34.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'Pre-Roll',
      tag: 'Opr2',
      images: ["assets/offer/offer3.png"],
      title: 'Diamond Dust',
      brand: 'Fig Farm',
      price: 40,
      size: 3.5,
      discount: 25,
      rating: 4.1,
      thc: 34.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'Ofl2',
      images: ["assets/offer/offer4.png"],
      title: 'Bubble Bath',
      brand: 'Jar Head',
      price: 45,
      size: 3.5,
      discount: 15,
      rating: 4.1,
      thc: 34.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'Ofl3',
      images: ["assets/offer/offer5.png"],
      title: 'Tropicana Shake',
      brand: 'Grizzly Peak',
      price: 55,
      size: 3.5,
      discount: 10,
      rating: 4.1,
      thc: 34.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'Edibles',
      tag: 'OEd1',
      images: ["assets/offer/offer6.png"],
      title: 'Sauce Watermelon',
      brand: 'Kiva',
      price: 35,
      size: 3.5,
      rating: 4.1,
      discount: 20,
      thc: 34.4,
      type: 'Edibles',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'Ofl4',
      images: ["assets/offer/offer7.png"],
      title: 'Mountain Sage',
      brand: 'Cannabiotix',
      price: 45,
      size: 3.5,
      discount: 25,
      rating: 4.1,
      thc: 34.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'Pre-Roll',
      tag: 'Opr3',
      images: ["assets/offer/offer9.png"],
      title: 'El Guapo',
      brand: 'Green Dragon',
      price: 50,
      size: 3.5,
      discount: 15,
      rating: 4.1,
      thc: 34.4,
      type: 'Flower',
      description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
];
/*List<Product> bestSellerList = [
  Product(
      product: 'edibles',
      tag: 'ed9',
      images: ["assets/edibles/e9.png"],
      transparentImages: ["assets/edibles/e9.png"],
      title: "Juicy Melon 1:1 ",
      brand: 'Mindy\'s ',
      rating: 4.1,
      pack: '20ct',
      price: 30,
      thc: '100 MG',
      type: 'Gummy',
      isHybrid: true,
      stockPieces: 50,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'flower',
      tag: 'flw9',
      images: ["assets/flowers/flt/flt11.png"],
      title: "Pacific Chemistry Fogg",
      brand: 'Fog City Farms',
      size: 7,
      price: 75,
      type: 'Flower',
      description:
          'Our Foggies premium smalls come in a 7g bag. No shake, same high quality flower as in our jars...just smaller nugs. This powerful strain can bring relaxation as well as open up your creative, artistic senses. It has earthy fuel notes with a sweet and sour floral backend. Pacific Chemistry is the cousin of Fog City’s staple, Pacific Gas, also being fuel forward but with a sour addition that adds a more buzzy mental stimulation to its effects.',
      rating: 4.1,
      comment: 28,
      thc: '39.6%',
      isHybrid: true,
      stockPieces: 81),
  Product(
      product: 'preRoll',
      tag: 'pre4',
      images: ["assets/preRoll/pre9.png"],
      title: "Bogeyman Preroll",
      brand: 'Slims',
      rating: 4.1,
      price: 16,
      size: 1,
      comment: 19,
      thc: '28.1%',
      cbd: '0.2%',
      isHybrid: true,
      type: 'PreRolls',
      stockPieces: 82),
  Product(
      product: 'preRoll',
      tag: 'pre5',
      images: ["assets/preRoll/pre10.png"],
      title: "Butterstuff Preroll",
      brand: 'Ozone',
      rating: 4.1,
      size: 1,
      price: 16,
      comment: 19,
      thc: '28.1%',
      cbd: '0.2%',
      isSativa: true,
      type: 'PreRolls',
      stockPieces: 47),
  Product(
      product: 'concentrate',
      tag: 'ext9',
      images: [
        "assets/concentrates/west_cost_sour_lemon.png",
      ],
      transparentImages: [
        "assets/concentrates/west_cost_sour_lemon.png",
      ],
      title: "Sour Lemon Sauce",
      size: 1,
      brand: 'FloraCal',
      rating: 4.1,
      price: 60,
      comment: 5,
      thc: '74%',
      isSativa: true,
      type: 'Live Rosin',
      stockPieces: 33,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'vaporizers',
      tag: 'vap9',
      images: ["assets/vaporizers/v9.png"],
      title: "Juicy Melon",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 1,
      price: 75,
      thc: '74%',
      isHybrid: true,
      type: 'Cartridge',
      stockPieces: 19,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'edibles',
      tag: 'ed9',
      images: ["assets/edibles/e9.png"],
      transparentImages: ["assets/edibles/e9.png"],
      title: "Juicy Melon 1:1 ",
      brand: 'Mindy\'s ',
      rating: 4.1,
      pack: '20ct',
      price: 30,
      thc: '100 MG',
      type: 'Gummy',
      isHybrid: true,
      stockPieces: 50,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'beverages',
      tag: 'b5',
      images: ["assets/beverages/b5.png"],
      title: "The Big Bang Pack",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 216,
      type: 'Tonic',
      thc: '5 MG',
      stockPieces: 19,
      description:
          'Thirsty for something different? Grab our new Starter Pack and see why Cann is the best thing to happen to drinking since drinking. Discover your favorite flavor with this limited-edition bundle.\n\n\nBundle includes:\n\nOne 6 pack of Blood Orange Cardamom.\nOne 4 pack of Blood Orange Cardamom Hi Boys.One 8 pack of Blood Orange Cardamom Roadies.\nOne 6 pack of Lemon Lavender.\nOne 4 pack of Lemon Lavender Hi Boys.\nOne 8 pack of Lemon Lavender Roadies.\nOne 6 pack of Grapefruit Rosemary.\nOne 4 pack of Grapefruit Rosemary Hi Boys.\nOne 8 pack of Grapefruit Rosemary Roadies'),
  Product(
      product: 'tinctures',
      tag: 'tin1',
      images: ["assets/tinctures/t1.png"],
      title: "Drift Away",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 30,
      totalThc: '300 MG',
      thc: '300 MG',
      ml: 30,
      flOz: 1,
      isIndica: true,
      type: 'Dropper',
      stockPieces: 20),
];
List<Product> newBeginnerList = [
  Product(
      product: 'Pre-Roll',
      tag: 'Opr2',
      images: ["assets/offer/offer3.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 65,
      size: 3.5,
      discount: 25,
      rating: 4.1,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'Ofl3',
      images: ["assets/offer/offer5.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 65,
      size: 3.5,
      discount: 10,
      rating: 4.1,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'Ofl4',
      images: ["assets/offer/offer7.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 45,
      size: 3.5,
      discount: 25,
      rating: 4.1,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'concentrate',
      tag: 'ext7',
      images: [
        "assets/concentrates/west_coast_peach_rings.png",
      ],
      transparentImages: [
        "assets/concentrates/west_coast_peach_rings.png",
      ],
      title: "Peach Rings Badder",
      brand: 'Verano',
      rating: 4.1,
      price: 60,
      size: 1,
      comment: 27,
      thc: '74%',
      type: 'Live Rosin',
      isHybrid: true,
      stockPieces: 50,
      description:
          "each  Live Resin Badder from WCC is an Indica-dominant concentrate that’s packed with copious amounts of THC and a loud fruit flavor. The effects from these dabs produce a strong, euphoric high that generates a relaxing and tranquil mindset. With a gassed-up peachy exhale, this live resin badder provides comfort for the distressed high-tolerance consumer."),
  Product(
      product: 'preRoll',
      tag: 'pre4',
      images: ["assets/preRoll/pre9.png"],
      title: "Bogeyman Preroll",
      brand: 'Slims',
      rating: 4.1,
      price: 16,
      size: 1,
      comment: 19,
      thc: '28.1%',
      cbd: '0.2%',
      isHybrid: true,
      type: 'PreRolls',
      stockPieces: 82),
  Product(
      product: 'concentrate',
      tag: 'ext9',
      images: [
        "assets/concentrates/west_cost_sour_lemon.png",
      ],
      transparentImages: [
        "assets/concentrates/west_cost_sour_lemon.png",
      ],
      title: "Sour Lemon Sauce",
      size: 1,
      brand: 'FloraCal',
      rating: 4.1,
      price: 60,
      comment: 5,
      thc: '74%',
      isSativa: true,
      type: 'Live Rosin',
      stockPieces: 33,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'edibles',
      tag: 'ed9',
      images: ["assets/edibles/e9.png"],
      transparentImages: ["assets/edibles/e9.png"],
      title: "Juicy Melon 1:1 ",
      brand: 'Mindy\'s ',
      rating: 4.1,
      pack: '20ct',
      price: 30,
      thc: '100 MG',
      type: 'Gummy',
      isHybrid: true,
      stockPieces: 50,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'tinctures',
      tag: 'tin1',
      images: ["assets/tinctures/t1.png"],
      title: "Drift Away",
      brand: 'Yummi Karma',
      rating: 4.1,
      price: 30,
      totalThc: '300 MG',
      thc: '300 MG',
      ml: 30,
      flOz: 1,
      isIndica: true,
      type: 'Dropper',
      stockPieces: 20),
];
List<Product> newArrivalList = [
  Product(
      product: 'Pre-Roll',
      tag: 'Opr1',
      images: ["assets/offer/offer2.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 65,
      size: 3.5,
      rating: 4.1,
      discount: 20,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'Ofl2',
      images: ["assets/offer/offer4.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 65,
      size: 3.5,
      discount: 15,
      rating: 4.1,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'Edibles',
      tag: 'OEd1',
      images: ["assets/offer/offer6.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 35,
      size: 3.5,
      rating: 4.1,
      discount: 20,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'Pre-Roll',
      tag: 'Opr3',
      images: ["assets/offer/offer9.png"],
      title: 'Lorem Ipsum ',
      brand: 'Cannabis Brand',
      price: 50,
      size: 3.5,
      discount: 15,
      rating: 4.1,
      thc: '34.4%',
      type: 'Flower',
      description:
          'Like a morning cup of tea, Ice Fog’s terpenes are rich and creamy with a hint of lemon and are known for creating a nice body high and mildly relaxing feelings. Like the weather system it’s named for, Ice Fog also features a particularly frosty resin coating on each oversized, beautiful nug. We recommend enjoying Ice Fog at your next low-key gathering, like a dinner party with friends or when watching a cute yet heartfelt rom-com with your significant other on your preferred streaming service.',
      comment: 55,
      isHybrid: true,
      stockPieces: 80),
  Product(
      product: 'flower',
      tag: 'flw9',
      images: ["assets/flowers/flt/flt11.png"],
      title: "Pacific Chemistry Fogg",
      brand: 'Fog City Farms',
      size: 7,
      price: 75,
      type: 'Flower',
      description:
          'Our Foggies premium smalls come in a 7g bag. No shake, same high quality flower as in our jars...just smaller nugs. This powerful strain can bring relaxation as well as open up your creative, artistic senses. It has earthy fuel notes with a sweet and sour floral backend. Pacific Chemistry is the cousin of Fog City’s staple, Pacific Gas, also being fuel forward but with a sour addition that adds a more buzzy mental stimulation to its effects.',
      rating: 4.1,
      comment: 28,
      thc: '39.6%',
      isHybrid: true,
      stockPieces: 81),
  Product(
      product: 'preRoll',
      tag: 'pre5',
      images: ["assets/preRoll/pre10.png"],
      title: "Butterstuff Preroll",
      brand: 'Ozone',
      rating: 4.1,
      size: 1,
      price: 16,
      comment: 19,
      thc: '28.1%',
      cbd: '0.2%',
      isSativa: true,
      type: 'PreRolls',
      stockPieces: 47),
  Product(
      product: 'vaporizers',
      tag: 'vap9',
      images: ["assets/vaporizers/v9.png"],
      title: "Juicy Melon",
      brand: 'Stiiizy',
      rating: 4.1,
      size: 1,
      price: 75,
      thc: '74%',
      isHybrid: true,
      type: 'Cartridge',
      stockPieces: 19,
      description:
          "Sour Lemon Live Resin Sauce by West Coast Cure is a Sativa leaning extract that merges the delicious and refreshing flavors of lemons and fruit punch. Instilling an upbeat mindset with a creative kicker, this citrus-centric sugar is known to energize, motivate, and arouse the consumer’s creative juices. A great daytime dab, Sour Lemon’s effects create a sense of inspired relaxation that motivates the psyche."),
  Product(
      product: 'beverages',
      tag: 'b5',
      images: ["assets/beverages/b5.png"],
      title: "The Big Bang Pack",
      brand: 'Cann',
      rating: 4.1,
      flOz: 12,
      ml: 355,
      calories: 50,
      price: 216,
      type: 'Tonic',
      thc: '5 MG',
      stockPieces: 19,
      description:
          'Thirsty for something different? Grab our new Starter Pack and see why Cann is the best thing to happen to drinking since drinking. Discover your favorite flavor with this limited-edition bundle.\n\n\nBundle includes:\n\nOne 6 pack of Blood Orange Cardamom.\nOne 4 pack of Blood Orange Cardamom Hi Boys.One 8 pack of Blood Orange Cardamom Roadies.\nOne 6 pack of Lemon Lavender.\nOne 4 pack of Lemon Lavender Hi Boys.\nOne 8 pack of Lemon Lavender Roadies.\nOne 6 pack of Grapefruit Rosemary.\nOne 4 pack of Grapefruit Rosemary Hi Boys.\nOne 8 pack of Grapefruit Rosemary Roadies'),
];*/

List<Product> monogramBannerModel = [
  Product(
      product: 'flower',
      tag: 'monogram1',
      images: ['assets/monogram/no2.jpg'],
      title: '2G',
      type: 'Medium',
      brand: 'Monogram',
      price: 40,
      size: 2,
      rating: 4.1,
      thc: 34,
      description:
      'Complex with a sweet, herby smell upfront that transitions to a skunky finish. No. 01 is a cerebral strain to help chill, focus, and confidently tackle obstacles in your path. Not too heavy. Not too light. Hits just right. The 2g jar offers cannabis perfected.\n ',
      comment: 55),
  Product(
      product: 'preRoll',
      tag: 'monogram3',
      images: ['assets/monogram/loosies.jpg'],
      title: 'Loosies Roll Pack',
      brand: 'Monogram',
      price: 40,
      size: 2,
      rating: 4.1,
      thc: 23.07,
      type: 'Medium',
      description:
      'A cerebral strain to help chill, focus and confidently tackle obstacles in your path. Complex with a sweet herby smell upfront that transitions to a skunky finish. Each LOOSIES pack contains four 0.5g prerolls, individually wrapped to create that perfect communal smoke.\n ',
      comment: 25),
  Product(
      product: 'flower',
      tag: 'monogram2',
      images: ['assets/monogram/no4.jpg'],
      title: '4G',
      brand: 'Monogram',
      price: 70,
      size: 4,
      rating: 4.1,
      thc: 34.9,
      type: 'Medium',
      description:
      'With initial aromas of sweet kush and mint, No. 03 invites you to step back and smell the flowers. Notes of grape, diesel and citrus lead into a powerful finish, encouraging you to take a hit, slow down, and enjoy the ride. Whether it’s just for you or for the group, the 4g jar invites you to extend your smoke.',
      comment: 55),
  Product(
      product: 'preRoll',
      tag: 'monogram4',
      images: ['assets/monogram/og_handroll.jpg'],
      title: 'The OG Handroll',
      brand: 'Monogram',
      price: 50,
      size: 3,
      rating: 4.1,
      thc: 27.5,
      type: 'PreRolls',
      description:
      'The first product of its kind, The OG Handroll takes inspiration from the smoke experience of a premium cigar, but implements a proprietary roll technique allowing the flower to burn slowly and evenly for multiple sessions.\n\n ',
      comment: 15),
];
