// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQwmt5nzkuKWMR_FQFt4bXZGNQlB6jdw',
    appId: '1:613744348808:web:a01f22ad3e8cf55bde193d',
    messagingSenderId: '613744348808',
    projectId: 'new-weedus',
    authDomain: 'new-weedus.firebaseapp.com',
    databaseURL: 'https://new-weedus-default-rtdb.firebaseio.com',
    storageBucket: 'new-weedus.appspot.com',
    measurementId: 'G-FR4ZKLH4WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3SRwG7DeayPZKUhbhf5uDb4tZ3viG_L0',
    appId: '1:613744348808:android:41c27d34860db1aade193d',
    messagingSenderId: '613744348808',
    projectId: 'new-weedus',
    databaseURL: 'https://new-weedus-default-rtdb.firebaseio.com',
    storageBucket: 'new-weedus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRv9-aCtlKipnFhIMiPzE9DvBRryKERTM',
    appId: '1:613744348808:ios:188a3f6b566907d1de193d',
    messagingSenderId: '613744348808',
    projectId: 'new-weedus',
    databaseURL: 'https://new-weedus-default-rtdb.firebaseio.com',
    storageBucket: 'new-weedus.appspot.com',
    iosClientId: '613744348808-r0k04gl24t3s168ibgtqaubb0h6e441p.apps.googleusercontent.com',
    iosBundleId: 'com.example.newWeedus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRv9-aCtlKipnFhIMiPzE9DvBRryKERTM',
    appId: '1:613744348808:ios:188a3f6b566907d1de193d',
    messagingSenderId: '613744348808',
    projectId: 'new-weedus',
    databaseURL: 'https://new-weedus-default-rtdb.firebaseio.com',
    storageBucket: 'new-weedus.appspot.com',
    iosClientId: '613744348808-r0k04gl24t3s168ibgtqaubb0h6e441p.apps.googleusercontent.com',
    iosBundleId: 'com.example.newWeedus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvQwmt5nzkuKWMR_FQFt4bXZGNQlB6jdw',
    appId: '1:613744348808:web:b1764e70a108728dde193d',
    messagingSenderId: '613744348808',
    projectId: 'new-weedus',
    authDomain: 'new-weedus.firebaseapp.com',
    databaseURL: 'https://new-weedus-default-rtdb.firebaseio.com',
    storageBucket: 'new-weedus.appspot.com',
    measurementId: 'G-54HW1JHFKC',
  );

}